################################################
#
#	MariaDB ���� ���� (MySQL �������� ȣȯ)
#
################################################
driver = org.mariadb.jdbc.Driver
url = jdbc:mariadb://localhost:3306/lin200?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&sslMode=DISABLE
id = root
pw = 1307

# ���ӱ� ��ü���� �ڵ��Ŀ� ����� ������ ��츸 ��밡��.
# �ڵ��Ŀ� ��� ����(true: ��� / false: ������)
is_donation = false
# �ڵ��Ŀ� ����
donation_url = jdbc:mariadb://localhost:3306/donation?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&sslMode=DISABLE

################################################
# �ڵ���� ������� ����
auto_backup = false
################################################
# �ڵ���� �ֱ� ����
#	������ ������ �ð��� �������� �����̰� ����.
#	�д���.
auto_backup_delay = 1

################################################
# ��� ��� ����.
#auto_backup_path = C:/backup
auto_backup_path = server_backup
